### ISSUE TITLE
Please wait before reconnecting!

### ISSUE THREAD

**Issue by Richard979-dev** [crpmax/mc-bots#11]
When I try to spam it says Please wait before reconnecting in new mc versions!

**Comment by crpmax** [comment]
Hello,
the kick message says everything.  This is standard minecraft server behavior called "connection throttle", which kick players that are connecting too fast. The default delay required is 4 seconds, so set the bot delay to that or higher using the `-d` option.
Example: `java -jar mc-bots.jar -s localhost -d 5000 7000` This sets the delay to 5-7 seconds.
