### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by xFreakss** [crpmax/mc-bots#13]
I've noticed that there is no way to change IPs when testing with those bots, so, can we have an switch to make bots disconnect right after conecting? My server limits to 3 connections through one IP.

And thanks for the awesome tool!

**Comment by crpmax** [comment]
Hello,
what you need is to use proxies, which my app doesn't support yet.
Now you can try it with [proxychains](https://github.com/haad/proxychains).

I may implement a function to use a proxy list in the future.
