### ISSUE TITLE
Every Time i try to run the app it says

### ISSUE THREAD

**Issue by WeihnachtsmannYT** [crpmax/mc-bots#19]
https://pastebin.pl/view/b72032c4 i don't know what i do wrong

**Comment by crpmax** [comment]
Hello,
is the server in offline mode?

**Comment by WeihnachtsmannYT** [comment]
No

**Comment by DogLoverPink** [comment]
This tool can only be used on servers that are offline.

set "online-mode:" to false in server.properties

**Comment by WeihnachtsmannYT** [comment]
thanks
