### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by 0ndras3k** [crpmax/mc-bots#2]
I recommend removing annotated parts such as
 "      //Log.info(Arrays.toString(message.getWith().toArray()));
        //msg = String.format(msg, );
        //return msg;
" which are completely useless here.

**Comment by crpmax** [comment]
Hi, thank you for advise.

8e89e2accbc8825dcf9bbefd93ec2b2d4b071606
eaaf092ae5ad1c7cb48a3ac0130f4d9d51d77a5c
