### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by daddymcmah** [crpmax/mc-bots#22]
hi I know this is a pretty stupid question but how do you use this? is there a guide or tutorial im missing?

**Comment by crpmax** [comment]
Hello,

this is a so-called CLI (command line interface) application.
It has no GUI (graphical user interface).
You have to run it in command prompt on Windows.

Assuming you are using Windows and you have Java installed, you can do the following:
- Download [the latest release jar file](https://github.com/crpmax/mc-bots/releases)
- Go to the download file location (usually Downloads folder) using Windows file explorer
- Click in the file location bar, type `cmd` and press enter - this should open Windows command prompt in the location
- Type the command to start the jar file. The basic usage is written [here](https://github.com/crpmax/mc-bots/blob/main/README.md#-usage).
 
Write `java -jar mc-bots-1.2.0.jar -s ADDRESS:PORT`, where the `mc-bots-1.2.0.jar` is the jar file name, `ADDRESS` is the Minecraft server IP or domain and `PORT` is the port of the server (usually 25565).
You can add options to the app listed [here](https://github.com/crpmax/mc-bots/blob/main/README.md#-options).
So it can look for example like this: `java -jar mc-bots-1.2.0.jar -s 192.168.0.189:25565`
Then press enter to start the app, and use Ctrl+C to exit the app.

Here I found a tutorial how to run a jar file in command prompt: https://www.youtube.com/watch?v=MhwX8_ohOD8

**Comment by ZekePolarisBSH** [comment]
Is there a version that works for server version 1.12?

**Comment by crpmax** [comment]
Hello,
I am afraid there is not.
The library I use is made for each exact version of the game and does not support multiple versions at once.
I think it would be possible to compile my app with the 1.12 version of the library, but it would require rewriting the code.
In the future, I plan to make my own library which would support multiple versions.

You can use alternative app like: [LambdaAttack](https://github.com/games647/LambdaAttack)
