### ISSUE TITLE
1.19 Support?

### ISSUE THREAD

**Issue by WarBringerLT** [crpmax/mc-bots#33]
Will there be 1.19 update?

**Comment by crpmax** [comment]
Hello,
my app is using this library: https://github.com/GeyserMC/MCProtocolLib/releases
So I can update as soon as the library is updated to 1.19.

**Comment by WarBringerLT** [comment]
Thank you so much for fast response! I will wait... patiently.... haha, hopefully it'll come out soon. Thanks!
