### ISSUE TITLE
1.19 support

### ISSUE THREAD

**Issue by EthanVolker** [crpmax/mc-bots#35]
Would it be possible to update for 1.19 support.
The library has been updated; https://github.com/GeyserMC/MCProtocolLib/releases

**Comment by TOWUK** [comment]
+

**Comment by crpmax** [comment]
Hello,
I know about it.
I will update as soon.

**Comment by TOWUK** [comment]
> Hello, I know about it. I will update soon.

thanks <3

**Comment by crpmax** [comment]
Updated https://github.com/crpmax/mc-bots/releases/tag/v1.2.4
