### ISSUE TITLE
Solved

### ISSUE THREAD

**Issue by FungY911** [crpmax/mc-bots#38]
after gradlew or gradlew build show me this error. Please can you help me?

Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

**Comment by crpmax** [comment]
Hello, please download and install standalone gradle.
https://gradle.org/install/

Next, use `gradle build` in the project directory and it should compile.

The reason for the error is a missing gradle-wrapper in my repository.

**Comment by crpmax** [comment]
I added the gradle-wrapped, so it should work now with the gradlew.bat
