### ISSUE TITLE
Proxy switching

### ISSUE THREAD

**Issue by RandomVersion** [crpmax/mc-bots#39]
1. load proxies from a file or url
2. select a random one 
3. use it 
4. repeat

**Comment by crpmax** [comment]
Hello,
Currently the way it works is to load a file or a file from a URL and use the proxies one by one in sequence and then repeat the cycle after the last proxy is used.

Why pick proxies randomly if they are already randomly in the file?

**Comment by RandomVersion** [comment]
oh my bad
