### ISSUE TITLE
1.16.5

### ISSUE THREAD

**Issue by Valdoum** [crpmax/mc-bots#4]
Is it possible to upgrade it to the new verison  ?

**Comment by crpmax** [comment]
Hi,
because my app is dependent on [MCProtocolLib](https://github.com/Steveice10/MCProtocolLib), which doesn't support this version yet, I can't update it.
You can make issue there, and ask for the update.
I will update my app ASAP, when the new version of the library is released.

**Comment by crpmax** [comment]
I have read your [issue](https://github.com/Steveice10/MCProtocolLib/issues/624), and I realized that neither you nor I tested it.
So I did now. It just works:
![WindowsTerminal_2021-04-06_22-42-24](https://user-images.githubusercontent.com/38163280/113776388-2b8ccb00-972a-11eb-80c2-7fff60aeffb9.png)
To be sure, I added it to README. 1f940aea144e3d233adbb43f2f9c7edea8c2c468
