### ISSUE TITLE
Cannot reply to ClientboundHelloPacket without profile and access token

### ISSUE THREAD

**Issue by Joshuak52** [crpmax/mc-bots#40]
Hello, I am trying to run a stress test no my server but getting an error?
Server Version: Paper 1.19-61.jar
MC-Bots Version: mc-bots-1.2.2

![2022-08-04_15-53-42](https://user-images.githubusercontent.com/38163280/182864502-18ef77ba-451f-4ac4-937c-c9f82f9d2160.png)

**Comment by crpmax** [comment]
Hello,
my app does not support version 1.19 yet.
I will update soon.

Also, is your server in offline mode (warez)?

Next time, please be careful about covering your server IP address, as somebody may misuse it.

**Comment by Joshuak52** [comment]
> Hello, my app does not support version 1.19 yet. I will update soon.
> 
> Also, is your server in offline mode (warez)?
> 
> Next time, please be careful about covering your server IP address, as somebody may misuse it.

Okay I didn't realize it mattered what version if the server was using viaversion.
Also, the server is not in offline mode but it is running Geyser

I don't have any proxy front end for the server so I don't think hiding the IP matters for me but thanks anyways!

**Comment by crpmax** [comment]
Hello,
please try it now with newer version https://github.com/crpmax/mc-bots/releases/tag/v1.2.4

**Comment by Joshuak52** [comment]
Hi, 
I am still getting the "Cannot reply to ClientboundHelloPacket without profile and access token." error. 
I believe this is caused by my server supporting Geyser (bedrock) and having floodgate installed. 

Would there be any work around to this? Thanks!

**Comment by crpmax** [comment]
I noticed you wrote 

> Also, the server is not in offline mode but it is running Geyser

So, I really think it could be the problem. My app does not support online mode bots.

**Comment by crpmax** [comment]
Online mode support will be in next version.
