### ISSUE TITLE
Feature request [SINGLE-BOT CONTROL]

### ISSUE THREAD

**Issue by LeoBlox5128** [crpmax/mc-bots#48]
The feature to only control a single bot would be really useful.

By typing in chat something like "ctrl BotName1", an user should only type commands/messages as that bot. Then, by typing "ctrl" without any arguments, it should control all bots again.

That's only what I imagine it would be like though. If you have any better ideas, use those.
This would also be really useful when testing features in the server while under stress.

**Comment by crpmax** [comment]
Hi,
this feature should be in next version.
