### ISSUE TITLE
Spammer doesn't work

### ISSUE THREAD

**Issue by xanderul** [crpmax/mc-bots#5]
Hello
The spammed doesn't work
How can i fix?
![Screenshot_3](https://user-images.githubusercontent.com/66251951/113897038-2d5e9900-97d3-11eb-97bd-6cf43ccb95a9.png)

I have Java 8 JDK
![Screenshot_2](https://user-images.githubusercontent.com/66251951/113896862-ff795480-97d2-11eb-9a1c-c2dc6040895e.png)

**Comment by xanderul** [comment]
sorry, i doesn't put ip:port

**Comment by crpmax** [comment]
Hi,
this is my fault and I am sorry for the inconvenience.
It is already fixed in source, but it is not in the v1.0.0 release.
4ba567deab3dfafcc61ded11e7c57f7222490dd4
