### ISSUE TITLE
Custom Commands

### ISSUE THREAD

**Issue by arnav335** [crpmax/mc-bots#51]
Hi! I am working on a project in which I will be creating a localhost website with all the features that mcstorm.io provides. Since I am a developer of javascript I used mineflayer api, the worst drop back about that api is it doesn't support 1.19.2/1 right now. So, kindly tell me the possible way for making your bots do custom actions like moving . Thanks :)

**Comment by TheBlankMindsNetwork** [comment]
bro i think i used your program tho latlely ITS NOT WORKING idk how to fix it

**Comment by crpmax** [comment]
> Hi! I am working on a project in which I will be creating a localhost website with all the features that mcstorm.io provides. Since I am a developer of javascript I used mineflayer api, the worst drop back about that api is it doesn't support 1.19.2/1 right now. So, kindly tell me the possible way for making your bots do custom actions like moving . Thanks :)

Hello,
my application currently does not provide any kind of API you can use.
Also, bot movement is not currently implemented.
I am using the [MCProtocolLib](https://github.com/GeyserMC/MCProtocolLib) library, which provides low-level access to the Minecraft protocol. That means you must write the code for movement and other actions yourself.
If you are familiar with Java, you could use parts of my app to write your own app and do the thing you want.

If you just want to run the app and control it, you can run it as a process in the background and send input to it to write chat messages. (doable in NodeJS).
