### ISSUE TITLE
Bots disconnecting??

### ISSUE THREAD

**Issue by TheRookie5619** [crpmax/mc-bots#53]
So I have used Java before I have the command and everything and proxies. I tested it on my own server, Nothing happened I checked command prompt and the proxies were working the accounts were being made although a few seconds later they 'disconnected' then the the command would end saying all bots disconnected.
Java -jar mc.jar -s (the ip) -p MCBOT_ -c 5 -t SOCKS4 -l socks4.txt -r
This is the command I used and 333 of the proxies were working.
And my java its the the on the latest version, and im using windows 10

**Comment by crpmax** [comment]
Hello,

please provide the full app console output.

**Comment by cevxl** [comment]
I think the cause could be that you're using a cracked server (obviously), and you have a login plugin which kicks the bots after a period of time.
