### ISSUE TITLE
Using - inside the ip of the server

### ISSUE THREAD

**Issue by PatienceHX** [crpmax/mc-bots#56]
So, i'm a developer for a little server me and my friends own and they don't know how to get the numeric ip for the server (goofy ahh hosting) so we want to use the domain of the server which looks something like this: xxxx.xxxx-xxxxxxxx.xx 
There is a - in there which makes the program crash, any ideas on how i could implement myself that or just wait for an update?

**Comment by crpmax** [comment]
Hello,
I don't think a dash in the address could cause an error.
Please provide the log.

You can get the server's IP and port from a site like this: https://mcsrvstat.us/
and then try it.
