### ISSUE TITLE
Add proxy support 

### ISSUE THREAD

**Issue by xanderul** [crpmax/mc-bots#6]
Hello,
This program needs to adapt proxy support because it will help server owners when the test server has "connection-throttle"

**Comment by xanderul** [comment]
and how can i contact you

**Comment by crpmax** [comment]
Hi,
if you are the owner of the server, you should change the `connection-throttle` for the test.
You can always connect the bots with some delay. The default is 4-5 seconds, which is enough for the default `connection-throttle` of 4 seconds. 
You can change the connection delay with this parametr: `-d <min> <max>`

I plan to add proxy support in the future.

You can contact me via email: `creepermaxcz (at) gmail (dot) com`

**Comment by xanderul** [comment]
thank you
