### ISSUE TITLE
Feature request: Multiple message lines OR /register and /login commands

### ISSUE THREAD

**Issue by VladOliinyk** [crpmax/mc-bots#65]
The bot does not fully cover the stress testing capabilities of my own server.

Banal authorization plugins already nullify all the bot's attempts to spam the chat.

If you put in the option -j command register password password - the bot will register, yes, but continue to spam the command that is visible only in the console.

If you run the bot again, with the argument -j /login password then the bot will log in, right, but again, will not write anything to the chat as it continues to try to "log in".

It would be great to set up a similar file functionality for the option to send messages, like for proxies or nicknames. In the file you can specify a few lines with messages that will send the bot.

This would solve most problems. It would also help test the security of the server a bit better. Since many anti-bots can easily handle such primitive bot attacks.

**Comment by crpmax** [comment]
Hi, made a commit with this feature, but it is not in release yet.
d205bd7

Multiple commands would be joined using `&&` symbol.
It should work like this:
 `java -jar mc-bots.jar -j "/register pass pass && /login pass && Hello world!"`

```
[10:48:03] [Server thread/INFO]: zwnO5SMP5cHAaFEd issued server command: /register pass pass
[10:48:03] [Server thread/INFO]: zwnO5SMP5cHAaFEd issued server command: /login pass
[10:48:03] [Async Chat Thread - #0/INFO]: [Not Secure] <zwnO5SMP5cHAaFEd> Hello world!
```

**Comment by crpmax** [comment]
Feature was added in v1.2.6
