### ISSUE TITLE
 Any plans to support 1.12.2~1.17?

### ISSUE THREAD

**Issue by xiaozhu2007** [crpmax/mc-bots#66]
I could not use it when join the older Minecraft versions.

Thx.

**Comment by crpmax** [comment]
Hi,
I am using the https://github.com/GeyserMC/MCProtocolLib lib that does not support multiple versions.
I may use other libraray that has multiversion support in the future.

**Comment by xiaozhu2007** [comment]
Thx, I will wait for updates!

**Comment by xiaozhu2007** [comment]
Maybe you can use the ViaVersion API.
reference: https://github.com/AlexProgrammerDE/ServerWrecker

**Comment by crpmax** [comment]
I may use other protocol library in version 2, but now it is hard to rewrite.
