### ISSUE TITLE
Request for Adding HTTP Proxy Option

### ISSUE THREAD

**Issue by pthmz** [crpmax/mc-bots#76]
I would like to request the addition of an HTTP proxy option to this program. HTTP proxies are more prevalent on the internet, and they are generally easier to obtain than other types of proxies. Adding this feature would enhance the program's usability and accessibility for a wider range of users.

Feature Request:

Name: HTTP Proxy Support
Description: Add an option within the program settings to configure an HTTP proxy. This would enable users to route their program's network requests through an HTTP proxy, providing flexibility and compatibility with various network environments.
Rationale: HTTP proxies are widely available and commonly used for network traffic management and security. By incorporating HTTP proxy support, the program can cater to users who rely on HTTP proxies for their internet connectivity needs.
Benefits:
Improved accessibility for users with HTTP proxies.
Enhanced program usability in diverse network configurations.
Expanded user base and increased program adoption.

**Comment by crpmax** [comment]
Hello,
I will look at it in next release.
