### ISSUE TITLE
Support 1.20.2

### ISSUE THREAD

**Issue by ondrejnedoma** [crpmax/mc-bots#82]
**Describe the bug**
1.20.2 not supported

**To Reproduce**
1. Run the program on a 1.20.2 server
2. Observe that the clients won't connect

**Expected behavior**
The clients connect

**Screenshot or app console output**
![image](https://github.com/crpmax/mc-bots/assets/117393974/fcad32df-c063-487e-a6db-ac9ca4cc9241)

**Whole command used to start the app**
java -jar mc-bots-1.2.8.jar -s REDACTED:25565 -p BOT_ -d 60000 70000 -c 10 -r

**Additional context**

**Comment by crpmax** [comment]
Updated. Download latest release.
https://github.com/crpmax/mc-bots/releases/tag/v1.2.9
