### ISSUE TITLE
Support 1.20.4

### ISSUE THREAD

**Issue by muelleel** [crpmax/mc-bots#83]
**Is your feature request related to a problem? Please describe.**
1.20.4 is currently not supported
`[23:25:26] INFO |  -> Outdated client! Please use 1.20.4`

**Describe the solution you'd like**
Being able to connect to 1.20.4 Servers

**Comment by crpmax** [comment]
Updated.
https://github.com/crpmax/mc-bots/releases/tag/v1.2.10
